### ISSUE TITLE
Use GitHub Flow?

### ISSUE THREAD

**Issue by charlesroper** [FieldStudiesCouncil/tombiovis#67]
@FieldStudiesCouncil/biodiversity @FieldStudiesCouncil/dev So we can better manage the commits of multiple developers, I'd like to propose we use the simple GitHub Flow system of branch creation -> pull request -> discuss -> merge to avoid messing up the master branch.

Details here: https://guides.github.com/introduction/flow/

Rich, if you're making changes, you're obviously allowed to commit directly to master (unless you want to have a discussion about a change).

**Comment by burkmarr** [comment]
It’s a good idea. It’s the flow I’ve been using here for Indicia – I have full commit permission, but I always create a pull request so that John van Breda can review and merge himself since he has the best overview of the whole project.

Rich

**Comment by charlesroper** [comment]
Great! Andy has prepared a commit to revert the changes regarding recent vulnerabilities. He'll put them on a branch and issue a pull request for you to review. Should be a good test of the process. 👍

Charles

**Comment by burkmarr** [comment]
Good stuff.

**Comment by burkmarr** [comment]
I'm doing a bit of work just to fix a couple of bugs - recently reported - and tidy up documentation to make a release 1.9.0. I think the main outstanding task now is update documentation unless you think there is anything else (@charlesroper) that we should address. I am doing this during a week's A/L so I don't want do anything major, but we are really overdue moving from 1.9-alpha to 1.9.  I will also email the steering committee before release.

I've branched rel-1.9 straight off master since we don't yet have a devel branch.

When the documentation - PDFs - are updated and 1.9 released I will also update the main Identikit page on FSC website. I want to remove the videos as these are now very out of date (and therefore misleading) and I don't have time to create new ones. I'm thinking that we should keep the main Identikit page on the FSC website fairly minimal and point people to the the project's GitHub pages which I will beef up.

**Comment by charlesroper** [comment]
All sounds good to me and agree the videos should be removed if they are out of date. Also agree with keeping the FSC website minimal and beefing up the GH pages - the latter are much easier to work with (I like using Markdown to author technical docs) and easier to invite collaborators.

One question: why use PDF documentation rather than Markdown/HTML (e.g. on GH as a set of static pages)? **No need to act on it right now** - just thinking out loud. The rationale is that HTML is more accessible and flexible (e.g., better suited to variety of devices) and can be converted into PDF and epub quite easily. Here are a few of examples of people publishing an HTML ebook online, along with options to download in other formats:

- https://leanweb.dev/ (I know this guy and can ask him how he automates his process)
- https://resilientwebdesign.com/
- https://every-layout.dev/

Here is some guidance on the problems with PDF: https://gds.blog.gov.uk/2018/07/16/why-gov-uk-content-should-be-published-in-html-and-not-pdf/ (there's a good discussion under this article, too which shows how there is no "one size fits all" approach - worth a read)

**Comment by burkmarr** [comment]
Good point about documentation. I will update the Word documents (that I use to generated the PDFs) this time - in the interests of doing it quickly - but perhaps in future we could move to Markdown for these.

**Comment by burkmarr** [comment]
I've just created a long term 'develop' branch off master. As well as master and develop, we have a third long-term branch - gh-pages - which is required for the GitHub pages.
